config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]

  get 'different-hi', to: 'portfolios#differenthi'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'


  resources :categories
  resources :testers
  resources :posts
  resources :portofolios
  get 'pages/home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'portfolios/index'
  get 'portfolios/new'

  resources :blogs do
    member do
      get :toggle_status
    end
  end


  root to: 'pages#home'

  # For details on the DSL available with	in this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tester.rb
class Tester < ApplicationRecord
end

app/controllers/testers_controller.rb
class TestersController < ApplicationController
  before_action :set_tester, only: [:show, :edit, :update, :destroy]

  # GET /testers
  # GET /testers.json
  def index
    @testers = Tester.all
  end

  # GET /testers/1
  # GET /testers/1.json
  def show
  end

  # GET /testers/new
  def new
    @tester = Tester.new
  end

  # GET /testers/1/edit
  def edit
  end

  # POST /testers
  # POST /testers.json
  def create
    @tester = Tester.new(tester_params)

    respond_to do |format|
      if @tester.save
        format.html { redirect_to @tester, notice: 'Tester was successfully created.' }
        format.json { render :show, status: :created, location: @tester }
      else
        format.html { render :new }
        format.json { render json: @tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testers/1
  # PATCH/PUT /testers/1.json
  def update
    respond_to do |format|
      if @tester.update(tester_params)
        format.html { redirect_to @tester, notice: 'Tester was successfully updated.' }
        format.json { render :show, status: :ok, location: @tester }
      else
        format.html { render :edit }
        format.json { render json: @tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testers/1
  # DELETE /testers/1.json
  def destroy
    @tester.destroy
    respond_to do |format|
      format.html { redirect_to testers_url, notice: 'Tester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tester
      @tester = Tester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tester_params
      params.require(:tester).permit(:title)
    end
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/views/testers/_form.html.erb
<%= form_with(model: tester, local: true) do |form| %>
  <% if tester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tester.errors.count, "error") %> prohibited this tester from being saved:</h2>

      <ul>
      <% tester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testers/edit.html.erb
<h1>Editing Tester</h1>

<%= render 'form', tester: @tester %>

<%= link_to 'Show', @tester %> |
<%= link_to 'Back', testers_path %>

app/views/testers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testers.each do |tester| %>
      <tr>
        <td><%= tester.title %></td>
        <td><%= link_to 'Show', tester %></td>
        <td><%= link_to 'Edit', edit_tester_path(tester) %></td>
        <td><%= link_to 'Destroy', tester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tester', new_tester_path %>

app/views/testers/new.html.erb
<h1>New Tester</h1>

<%= render 'form', tester: @tester %>

<%= link_to 'Back', testers_path %>

app/views/testers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tester.title %>
</p>

<%= link_to 'Edit', edit_tester_path(@tester) %> |
<%= link_to 'Back', testers_path %>