config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]

  get 'different-hi', to: 'portfolios#differenthi'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'


  resources :categories
  resources :testers
  resources :posts
  resources :portofolios
  get 'pages/home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'portfolios/index'
  get 'portfolios/new'

  resources :blogs do
    member do
      get :toggle_status
    end
  end


  root to: 'pages#home'

  # For details on the DSL available with	in this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies									
	accepts_nested_attributes_for :technologies,	#lambda== -> 
														reject_if: lambda {|attrs| attrs['name'].blank?}
	include Placeholder
	validates_presence_of :title, :body, :main_image, :thumb_image

	  	#cutom scopes
	def self.differenthi
		where(subtitle: 'different hi')
	end

	scope :hi, -> {where(subtitle: 'hi')}

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
		self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
	end
# if self.main_image==nil
# 	self.main_image="http://placehold.it/600x400"
# end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

	def index
		# @portfolio_items=Portfolio.differenthi
		# @portfolio_items=Portfolio.hi
		@portfolio_items=Portfolio.all
	end

	def differenthi
		@differenthi_portfolio_items=Portfolio.differenthi
	end
	def new
		@portfolio_item=Portfolio.new
		3.times { @portfolio_item.technologies.build }
	end

	def create 
		@portfolio_item=Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))
		respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
	       
	      else
	        format.html { render :new }
	        
	      end
	    end

	end

	def edit
	    	@portfolio_item=Portfolio.find(params[:id])
	end

	def update
		@portfolio_item=Portfolio.find(params[:id])
	    respond_to do |format|
	      if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
	        format.html { redirect_to @blog, notice: 'The record was successfully updated.' }

	      else
	        format.html { render :edit }
	        
	      end
    	end
 	end

 	def show
 		@portfolio_item = Portfolio.find(params[:id])
 	end

 	def destroy
 		@portfolio_item = Portfolio.find(params[:id])
 		
 		@portfolio_item.destroy

   	 	respond_to do |format|
      	format.html { redirect_to portfolios_url, notice: 'Record was successfully destroyed.' }
 		end
 	end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/differenthi.html.erb

<% @differenthi_portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%=portfolio_item.subtitle %></p>
    <p><%=portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?  %>
    <% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio items</h1>


<%= form_for(@portfolio_item) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
index.html.erb

<%= link_to "Create New Item", new_portfolio_path %>

<%#= new_portfolio_url %>


<% @portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%=portfolio_item.subtitle %></p>
    <p><%=portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?  %>
    <!-- if ! 대신 unless 가능 -->
    <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
    <%= link_to 'Delete portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
    

app/views/portfolios/new.html.erb
new.html.erb


<%= form_for(@portfolio_item) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb

<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<p><%= @portfolio_item.body %></p>

<h2>Technologies Used</h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%=t.name %></p>
<% end %>